# Generated by Django 5.0.6 on 2024-05-13 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
